# Generated by Django 5.0 on 2023-12-09 14:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExposantInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('raison_sociel', models.CharField(max_length=255)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('secteur_activite', models.CharField(choices=[('PI', 'Promoteur Immobilier'), ('OF', 'Organisme financier'), ('BEA', "Bureau d'étude / Architecture"), ('EC', 'Entreprise de Construction'), ('AI', 'Agence immobilière'), ('TH', 'Tourisme / Hôtel'), ('AP', 'Association professionnelle'), ('PM', 'Presse / Média')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numero_tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('ville', models.CharField(max_length=255)),
                ('id_inscription', models.CharField(default='IMOBDZFRDEB52344', editable=False, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('date_inscription', models.DateTimeField(auto_now=True)),
                ('logo_pdf', models.ImageField(default='../static/images/favicon/favicon_immobfrdz.png', upload_to='')),
            ],
        ),
    ]
