# Generated by Django 4.2.7 on 2023-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR5E08ED1F', editable=False, max_length=20, unique=True),
        ),
    ]
