# Generated by Django 5.0 on 2023-12-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0005_alter_inscription_id_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR1B2AC147', editable=False, max_length=20, unique=True),
        ),
    ]
