# Generated by Django 5.0 on 2023-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0006_alter_inscription_id_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR5A76AD0F', editable=False, max_length=20),
        ),
    ]
