# Generated by Django 4.2 on 2023-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobApp', '0009_alter_inscription_id_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id_inscription',
            field=models.CharField(default='IMOBDZFR870D11EF', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='logo_pdf',
            field=models.ImageField(default='C:\\Users\\youce\\OneDrive\\Desktop\\immob cefa\\immob_website\\immob-project-master\\immobProject\\static\\images/favicon/favicon_immobfrdz.png', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, upload_to='qr_codes'),
        ),
    ]
